![iSA logo](../iSA_logo.png)
### Materiały do zajęć Statystyka
#### Kurs Junior Data Scientist

**Wojciech Artichowicz**

## Prawdopodobieństwo warunkowe

Zbiór danych ze strony [kaggle](https://www.kaggle.com/jaimevalero/developers-and-programming-languages/version/2) dotyczący użycia języków programowania i technologii używanych przez developerów.

Zadanie: Na podstawie odpowiedzi respondentów określ prawdopodibeństwotego, że developer:
 - używa języka Python
 - używa środowiska Jupyter
 - używa środowiska Jupyter jeśli wiadomo, że używa języka Python
 - używa języka Python jeśli wiadomo, że używa środowiska Jupyter

**Wczytanie i przygotowanie danych** (nie jest to bezpośrednią częścią zadania z rachunku prawdopodobieństwa)

In [4]:
import pandas as pd #import biblioteki Pandas do łatwej manipulacji danymi

In [5]:
df = pd.read_csv("python_jupyter_data.csv", index_col=0) # wczytanie pliku z danymi
df.head() # wypisanie części pliku w postaci tabeli

,jupyter notebook,jupyter,jupyter-notebook,python,ipython,ipython-notebook
0,0.000000,0.0,0.0,0.010536,0.0,0.0
1,0.000000,0.0,0.0,0.028996,0.0,0.0
2,0.094105,0.0,0.0,0.185109,0.0,0.0
3,0.000000,0.0,0.0,0.000000,0.0,0.0
4,0.000000,0.0,0.0,0.000000,0.0,0.0

In [6]:
df1=pd.DataFrame() #utworzenie pustego data frame (obiektu Pandas przechowujacego dane)
df1["jupyter"] = (df["jupyter notebook"]+df["jupyter"]+df["jupyter-notebook"])>0 #wybranie wszystkich rekordów, w których wspomniano termin jupyter i przypisanie im wartości 1
df1["python"] = (df["python"]+df["ipython"]+df["ipython-notebook"])>0 #wybranie wszystkich rekordów, w któryc wspomniano pythona
df1.dropna(inplace=True) # usunięcie wartości brakujących, jeśli jakieś w ogóle są
del df #usunięcie oryginalnego data frame - nie będzie już potrzebny

df1.head() #wypisanie części tabelki zawierającej dane o Pythonie i Jupyterze

   jupyter  python
0    False    True
1    False    True
2     True    True
3    False   False
4    False   False

In [7]:
T = df1.describe() # podsumowanie utworzonej tabelki i zapisanie jej do zmiennej T
T

       jupyter python
count    17461  17461
unique       2      2
top      False  False
freq     16767   9438

**Obliczenie potrzebnych prawdopodobieństw**

In [8]:
N = T.loc["count"][0] # wybranie liczebności próby, tj . odpowiedzi respondentów N = 17461
Nj = sum(df1["jupyter"]) # liczba respondentów używająca technologii jupyter
Np = sum(df1["python"]) # liczba respondentów używająca pythona
Npj = sum( (df1["jupyter"]) & (df1["python"])) # liczba respondentów używająca jupytera oraz pythona

P = dict() # utworzenie słownika języka Python - wygodny do przechowywania prawdopodobieństw
P["jupyter"] = Nj / N # prawdopodobieństwo, ze respondent używa środowiska Jupyter
P["python"] = Np / N # prawdopodobieństwo, że respondent używa języka Python
P["jupyter and python"] = (Npj) / N # prawdopodobieństwo, że respondent używa jupytera oraz pythona
P["jupyter|python"] = P["jupyter and python"]/P["python"] # prawdopodobieństwo, że respondent używa jupytera jeśli używa pythona
P["python|jupyter"] = P["jupyter and python"]/P["jupyter"] # prawdopodobieństwo, że respondent używa pythona jeśli używa jupytera
P

{'jupyter': 0.03974571903098333,
 'python': 0.45948112937403357,
 'jupyter and python': 0.03596586678884371,
 'jupyter|python': 0.07827495949146206,
 'python|jupyter': 0.904899135446686}

**Do zadania można podejśc inaczej: Utworzyć tabelkę respondentów używających / nie używających Pythona oraz Jupytera i obliczyć odpowiednie prawdopodobieństwa. Oczywiście wyniki muszą wyjść identyczne**

In [ ]:
Npj # respondenci używający pythona oraz juptera (Python, jupyter)
Np_nj = sum( (df1["python"]==True) & (df1["jupyter"]==False)) # respondenci używający pythona ale nie jupytera (python, nie jupyter)
Nij = sum( (df1["python"]==False) & (df1["jupyter"]==True)) # respondenci używający jupytera z innym językiem niż python
Ni_nj = sum( (df1["python"]==False) & (df1["jupyter"]==False)) # respondenci nie używający pythona ani jupytera

sum([Npj,Np_nj,Nij,Ni_nj])==N # sprawdzenie czy liczba elementów jest równa liczbe obserwacji (zawsze należy to zrobić)

In [ ]:
df2 = pd.DataFrame({"Python":[Npj, Np_nj], "Inne":[Nij, Ni_nj]})
df2.rename(index={0:'Jupyter',1:'Nie Jupyter'}, inplace=True)
df2

In [ ]:
pd.crosstab(df1["jupyter"],df1["python"]) # wersja alternatywna - użycie wbudowanej funkcji pandas

In [ ]:
P1 = dict()
#prawdopodobieństwo używania języka python
P1["python"] = (628 + 7395) / N
P1["python"]

In [ ]:
# prawdopodobieństwo używania środowiska Jupyter
P1["jupyter"] = (66+628) / N
P1["jupyter"]

In [ ]:
P1["jupyter and python"] = 628 / N

In [ ]:
#prawdopodobieństwo użwania jupytera pod warunkiem używania pythona
P1["jupyter|python"] = 628/(628+7395)
P1["jupyter|python"]

In [ ]:
# prawdopodobieństwo używania pythona pod warunkiem używania Jupytera
P1["python|jupyter"] = 628/(66+628)
P1["python|jupyter"]

In [ ]:
print(P)
print(P1)

In [ ]:
#eksport zbioru używanego na zajęciach
df = pd.read_csv("user-languages.csv")
sel = df[["jupyter notebook","jupyter","jupyter-notebook","python","ipython","ipython-notebook"]]
sel.to_csv("python_jupyter_data.csv")
del sel
del df